### PR TITLE
fix #572

### LINKED ISSUE #572: Panic on client
```
Jun 17 17:19:39 hk.testnet.observatory drand-client ts="Wed, 17 Jun 2020 17:19:39 UTC" call=cli.go:137 level=warn client="failed to load URL" url=http://pl-sin.testnet.drand.sh err="Get \"http://pl-sin.testnet.drand.sh/info\": dial tcp 13.225.103.127:80: i/o timeout"
Jun 17 17:19:39 hk.testnet.observatory drand-client panic: runtime error: integer divide by zero
Jun 17 17:19:39 hk.testnet.observatory drand-client goroutine 88 [running]:
Jun 17 17:19:39 hk.testnet.observatory drand-client github.com/drand/drand/client/http.(*HealthMetrics).startObserve(0xc00000f3e0, 0x12be9a0, 0xc000036058)
Jun 17 17:19:39 hk.testnet.observatory drand-client /opt/drand-client/client/http/metric.go:39 +0x490
Jun 17 17:19:39 hk.testnet.observatory drand-client created by github.com/drand/drand/client/http.MeasureHeartbeats
Jun 17 17:19:39 hk.testnet.observatory drand-client /opt/drand-client/client/http/metric.go:19 +0x90
```

### PR DESCRIPTION
**Pull request by willscott**

### CODE REVIEW

File: client/http/metric.go [hunk 1]
```diff
@@ -16,7 +16,9 @@ func MeasureHeartbeats(ctx context.Context, c []client.Client) *HealthMetrics {
 		next:    0,
 		clients: c,
 	}
-	go m.startObserve(ctx)
+	if len(c) > 0 {
```
Comment (hsanjuan) [inline client/http/metric.go:19]: should it warn, log, die when there are no clients? Would this be an abnormal thing?

Comment (willscott) [reply client/http/metric.go:19]: based on our use of this in the client binary, it isn't a warning - it will happen in normal operation when the client is configured to use grpc or gossip randomness and does not have a valid http upstream endpoint
