### PR TITLE
Fix #413, close grpc connection

### LINKED ISSUE #413: pubsub relay overwhelms node with connections
```
drand.testnet1.drand drand[30811]: ts="Mon, 25 May 2020 21:01:52 UTC" call=daemon.go:31 level=info private_listen=0.0.0.0:4444 control_port=8888 public_listen=127.0.0.1:5555
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 5ms
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 10ms
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 20ms
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 40ms
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 80ms
May 25 21:03:00 drand.testnet1.drand drand[30811]: 2020/05/25 21:03:00 http: Accept error: accept tcp 127.0.0.1:9999: accept4: too many open files; retrying in 160ms
```

> It has some thousand connections to the gossip relay WTF

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

File: cmd/relay-gossip/node/relaynode.go [hunk 1]
```diff
@@ -158,6 +158,8 @@ func (g *GossipRelayNode) start(drandPublicGRPC string) {
 		err = g.workRelay(client)
 		if err != nil {
 			g.l.Warn(fmt.Sprintf("error relaying: %+v", err))
+			err = conn.Close()
+			g.l.Warn(fmt.Sprintf("error while closing connection: %+v", err))
```
Comment (alanshaw) [inline cmd/relay-gossip/node/relaynode.go:162]:
```suggestion
			if err != nil {
				g.l.Warn(fmt.Sprintf("error while closing connection: %+v", err))
			}
```

Comment (Kubuxu) [reply cmd/relay-gossip/node/relaynode.go]: I've tried to fix it too fast ;p
