### PR TITLE
fix #462

### LINKED ISSUE #462: `/public/latest` Expires headers might be in the past if drand stopped generating randomness
Unless I'm wrong, I think the API `/public/latest` continues to provide the last-issued randomness value even if the network is not generating randomness. This means that the dates caching headers will be already expired.

This would mean that if the network stops producing randomness, any CDN is essentially disabled for this endpoint. I am not sure we can have a good fix here (ideas?). The http-relays should cache the latest value though, if they don't already.

### PR DESCRIPTION
**Pull request by willscott**
expiry header should always be in the future

### CODE REVIEW

File: http/server.go [hunk 1]
```diff
@@ -272,7 +272,12 @@ func (h *handler) LatestRand(w http.ResponseWriter, r *http.Request) {
 	nextTime := time.Now()
 	if info != nil {
 		roundTime = time.Unix(chain.TimeOfRound(info.Period, info.GenesisTime, resp.Round()), 0)
-		nextTime = time.Unix(chain.TimeOfRound(info.Period, info.GenesisTime, resp.Round()+1), 0)
+		next := time.Unix(chain.TimeOfRound(info.Period, info.GenesisTime, resp.Round()+1), 0)
+		if next.After(nextTime) {
+			nextTime = next
+		} else {
+			nextTime = nextTime.Add(time.Second)
```
Comment (hsanjuan) [inline http/server.go:279]: I have mixed feelings with this... I'd rather set something like `info.Period/2`.. sure a new round might come before that but otherwise we are telling the CDN (main consumer of this info) to "please check again in 1 second" which is a bit too low.

Comment (willscott) [reply http/server.go:279]: yeah, wasn't sure what the right fallback was. info.period/2 works for me
